services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin1234
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432


  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    restart: always

volumes:
  db_data:
